@startuml

' 学生とその属性
class 学生
class 学生番号
学生番号 --> 学生

' 教職員とその属性
class 教職員
class 職員番号
職員番号 --> 教職員

' 会員とその属性
class 会員
class 会員番号
class 氏名
class メールアドレス
会員番号 --> 会員
氏名 --> 会員
メールアドレス --> 会員

' 学生・教職員と会員の関係
学生 --> 会員
教職員 --> 会員

' 予約情報
class 予約情報
class 予約日時
予約日時 --> 予約情報
会員 --> 予約情報

' 図書とその属性
class 図書
class 管理番号
class 書名
class 著者
class 出版社
class ISBN
管理番号 --> 図書
書名 --> 図書
著者 --> 図書
出版社 --> 図書
ISBN --> 図書

' 図書の種別
class 書籍
class 雑誌
書籍 --> 図書
雑誌 --> 図書

' 貸出情報
class 貸出情報
class 貸出日
class 返却日
貸出日 --> 貸出情報
返却日 --> 貸出情報
会員 --> 貸出情報
図書 --> 貸出情報

' 図書と予約情報の関係
図書 --> 予約情報

@enduml
