@startuml Robodogクラス図
skinparam classAttributeIconSize 0
hide circle

class RoboDog {
 -myName:string
 -myTime:int
 -goodMorning:string
 -goodAfternoon:string
 -goodNight:string
 -firstValue:int
 -secondValue:int
 -result:int

 +getMyName():string
 +setMyName():int
 +setNewTime():void
 +getMyGreeting():string
 +2つの整数を設定()
 +setTwoValue():void
 +setAddGetresult():int
}

@enduml
